language: python
python:
  - "3.8.2"
env:
  -DJANGO=2.2
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python tests.py
deploy:
  provider: heroku
  api_key:
    secure: <ENCRYPTED API KEY>
  app: travis-heroku
  on:
    repo: nikitabansal711/travis_test_app